version: '3.8'

services:
  database:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: recipe_manager
    environment:
      SA_PASSWORD: "sa"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433

  api:
    container_name: recipe_manager
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - database