spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=RecipeManager
    username: sa
    password: Stone@2019!
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2016Dialect
      ddl-auto: validate
