spring:
  datasource:
    url: jdbc:sqlserver://db;databaseName=RecipeManager
    username: sa
    password: recipe@2021!
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true
    hibernate:
      ddl-sequence: validate
